
[package]
name = "starklotto"
version = "0.1.0"
edition = "2023_10"
cairo-version = "2.8.2"
scarb-version = "2.8.2"
keywords = ["cairo", "contracts", "starknet"]

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.8.2"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.31.0" }

[[target.starknet-contract]]
casm = true
sierra = true

[scripts]
test = "snforge test"
